### ISSUE TITLE
Examples from different classes share same label.

### ISSUE THREAD

**Issue by Mrxuefei** [dragen1860/MAML-TensorFlow#2]
Hello,I find that you give a label range in (0,80) to each examplein a meta_batch.But it make me wonder whether it will make the CNN confused because you give some examples in the same class different labels,also you give some  examples in the different classes same label.

**Comment by dragen1860** [comment]
sorry, but i dont understand what u mean.
the label range is from 0 to 4 for 5 way exp.

**Comment by Mrxuefei** [comment]
Sorry I made some mistakes，but I’m still confused.
Let 's start from a ordinary CNN.For example,I want to train a model to classify dog,cat,fish,cow,sheep...etc.Then I assign all dogs'label to be 0,cats be 1,fish be 2...and let the CNN take different examples with their own labels as input, Iteratively do forward propagation and back propagation.Finally the trained CNN has the ability to map a "test dog example"  to 0, a"test cat example" to 1...etc.
But in your project,you assign the label "0" to examples from different classes. So in the training process, the CNN will get some input examples such as "a dog","a cat",but with the same label——“0”.In this case ,How the CNN get its ability to classify?

**Comment by dragen1860** [comment]
I think your comprehension may be inaccurate.
For the 5 categories in same episode, the class label 0-4 will be assigned to distinct classes. Hence, the `dog` and `cat` wont share the same class label **in one episode**.
However, this phenomenon occurred as expected when the two class in **different** episode since all label in episode are labeled **relatively**, for instance:
for `episode 1`:
```dog, cat, fish, tree, apple```
and for `episode 2`:
```cat, dog, laptop, mouse, cow```.
as you can tell, the `dog` in `episode 1 & 2` will have distinct label(0 vs 1).
similarly  the `cat` in `episode 1` and the `dog` in `episode 2` however, have the same label 1.
This is normal and we just consider relative indexing.
